### ISSUE TITLE
Software glitch and crush (Expansion Microscope)

### ISSUE THREAD

**Issue by JinlongL** [TheDeanLab/ASLM#1025]
```
(navigate) C:\Users\Dean-Lab>navigate
Exception in thread live Data:
Traceback (most recent call last):
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dean-Lab\Documents\navigate\src\navigate\model\model.py", line 951, in run_data_process
    self.show_img_pipe.send("stop")
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
Exception inside ObjectInSubprocess: Traceback (most recent call last):
  File "C:\Users\Dean-Lab\Documents\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 529, in _child_loop
    child_pipe.send((result, printed_output.getvalue()))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

Process Model:
Traceback (most recent call last):
  File "C:\Users\Dean-Lab\Documents\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 529, in _child_loop
    child_pipe.send((result, printed_output.getvalue()))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dean-Lab\Documents\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 533, in _child_loop
    child_pipe.send((Exception(str(e)), printed_output.getvalue()))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

(navigate) C:\Users\Dean-Lab>C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<3>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<4>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<5>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<6>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<7>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<8>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<9>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<1>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<2>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<3CB>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
navigate
Exception in thread live Data:
Traceback (most recent call last):
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dean-Lab\Documents\navigate\src\navigate\model\model.py", line 951, in run_data_process
    self.show_img_pipe.send("stop")
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
Exception inside ObjectInSubprocess: Traceback (most recent call last):
  File "C:\Users\Dean-Lab\Documents\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 529, in _child_loop
    child_pipe.send((result, printed_output.getvalue()))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

Process Model:
Traceback (most recent call last):
  File "C:\Users\Dean-Lab\Documents\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 529, in _child_loop
    child_pipe.send((result, printed_output.getvalue()))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dean-Lab\Documents\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 533, in _child_loop
    child_pipe.send((Exception(str(e)), printed_output.getvalue()))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<3>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<4>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<5>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<6>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<7>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<8>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<9>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<1>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<2>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  warnings.warn(
```
[model_debug.log](https://github.com/user-attachments/files/17548721/model_debug.log)

**Comment by AdvancedImagingUTSW** [comment]
It appears that the microscope was placing multiple images in the buffer before it was able to pull the frames from it. Some sort of latency probably caused this problem. Consequently, it could be that other processes on the computer were interfering, or perhaps the controller was getting backed up due to the histogram/MIP display. Difficult to diagnose. Next time please also provide the experiment file and keep an eye for other things that are open and running on the computer. Will state as low priority unless it comes back up.
