### ISSUE TITLE
Fresh Install

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#1039]
Just installed on a new computer, and I get this error. I suspect it is because git is not installed, but I wanted to log the information and then try it...

```
(base) C:\Users\DeanLab>conda activate navigate

(navigate) C:\Users\DeanLab>navigate -sh
Traceback (most recent call last):
  File "C:\Users\DeanLab\.conda\envs\navigate\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DeanLab\.conda\envs\navigate\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DeanLab\.conda\envs\navigate\Scripts\navigate.exe\__main__.py", line 4, in <module>
  File "C:\Users\DeanLab\Documents\GitHub\navigate\src\navigate\__init__.py", line 4, in <module>
    from ._commit import __commit__  # noqa: F401
  File "C:\Users\DeanLab\Documents\GitHub\navigate\src\navigate\_commit.py", line 109, in <module>
    __commit__ = get_git_revision_hash()
  File "C:\Users\DeanLab\Documents\GitHub\navigate\src\navigate\_commit.py", line 61, in get_git_revision_hash
    subprocess.check_output(
  File "C:\Users\DeanLab\.conda\envs\navigate\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\DeanLab\.conda\envs\navigate\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\DeanLab\.conda\envs\navigate\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\DeanLab\.conda\envs\navigate\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by AdvancedImagingUTSW** [comment]
Yeah, that was it... Although I had GitHub Desktop installed, I did not have Git for Windows installed. This is worth a try/except statement...

https://git-scm.com/downloads/win
