### ISSUE TITLE
Error on stop acqusition call after cancelling z-stack save in high res

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#350]
```
Traceback (most recent call last):
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\model.py", line 646, in run_data_process
    self.end_acquisition()  # Need this to turn off the lasers/close the shutters
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\model.py", line 568, in end_acquisition
    self.image_writer.close()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\features\image_writer.py", line 295, in close
    self.data_source.close()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\data_sources\tiff_data_source.py", line 237, in close
    self.metadata.to_xml(
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\metadata_sources\ome_tiff_metadata.py", line 195, in to_xml
    return super().to_xml(file_type, root=root, **kw)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\metadata_sources\metadata.py", line 197, in to_xml
    d = getattr(
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\metadata_sources\ome_tiff_metadata.py", line 120, in ome_tiff_xml_dict
    self.configuration["configuration"]["microscopes"][self.active_microscope][
  File "<string>", line 2, in __getitem__
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\multiprocessing\managers.py", line 825, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'N/A'
Exception inside ObjectInSubprocess: Traceback (most recent call last):
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\concurrency\concurrency_tools.py", line 521, in _child_loop
    result = getattr(obj, method_name)(*args, **kwargs)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\model.py", line 515, in run_command
    self.end_acquisition()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\model.py", line 568, in end_acquisition
    self.image_writer.close()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\features\image_writer.py", line 295, in close
    self.data_source.close()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\data_sources\tiff_data_source.py", line 237, in close
    self.metadata.to_xml(
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\metadata_sources\ome_tiff_metadata.py", line 195, in to_xml
    return super().to_xml(file_type, root=root, **kw)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\metadata_sources\metadata.py", line 197, in to_xml
    d = getattr(
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\metadata_sources\ome_tiff_metadata.py", line 120, in ome_tiff_xml_dict
    self.configuration["configuration"]["microscopes"][self.active_microscope][
  File "<string>", line 2, in __getitem__
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\multiprocessing\managers.py", line 825, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'N/A'

error message:  DCAMERR.TIMEOUT
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\controller\sub_controllers\acquire_bar_controller.py", line 247, in launch_popup_window
    self.parent_controller.execute("stop_acquire")
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\controller\controller.py", line 858, in execute
    self.sloppy_stop()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\controller\controller.py", line 896, in sloppy_stop
    self.model.run_command("stop")
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\concurrency\concurrency_tools.py", line 412, in attr
    return _get_response(self, True)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\concurrency\concurrency_tools.py", line 433, in _get_response
    raise resp
Exception: 'N/A'
```

**Comment by zacsimile** [comment]
I think @annie-xd-wang fixed this a while ago with 

```
for m in self.virtual_microscopes:
                image_writer = (
                    ImageWriter(
                        self, self.virtual_microscopes[m].data_buffer, m
                    ).save_image
                    if self.is_save
                    else None
                )
                threading.Thread(
                    target=self.simplified_data_process,
                    args=(
                        self.virtual_microscopes[m],
                        getattr(self, f"{m}_show_img_pipe"),
                        image_writer,
                    ),
                ).start()
```

But I can't find the commit where this happened because I Ruffed it up.
