### ISSUE TITLE
Frequent camera errors

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#408]
I'm getting an error related to the camera/DAQ line for the camera. It never breaks the program, so it is not a huge issue, but I didn't see it until recently.

Frequently, but not every time I acquire, I receive this error:

```
Exception in thread live signal:
Traceback (most recent call last):
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\model.py", line 847, in run_live_acquisition
    self.run_acquisition()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\model.py", line 862, in run_acquisition
    self.snap_image()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\model.py", line 831, in snap_image
    self.active_microscope.daq.run_acquisition()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\devices\daq\daq_ni.py", line 243, in run_acquisition
    self.camera_trigger_task.start()
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\site-packages\nidaqmx\task.py", line 1026, in start
    check_for_error(error_code)
  File "C:\Users\DeanLab\.conda\envs\ASLM\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: Task specified is invalid or does not exist.
Status Code: -200088
```

**Comment by zacsimile** [comment]
This error arises from multiple sources, each of which needs to be addressed individually. It is not necessarily related to the camera.
