### ISSUE TITLE
Galvo entry in waveform popup flummoxed by `.`

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#599]
```
2023-08-22 14:40:41,166 - model - ERROR - galvo_base: could not convert string to float: '.' waveform constants.yml doesn't have parameter amplitude/offset/frequency for Galvo 0
2023-08-22 14:40:41,186 - model - DEBUG - feature_container: running signal node: PrepareNextChannel
2023-08-22 14:40:41,202 - model - DEBUG - filter_wheel_sutter: SutterFilterWheel - Moving to Position 0
2023-08-22 14:40:41,337 - model - DEBUG - feature_container: SignalContainer - Traceback (most recent call last):
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\features\feature_container.py", line 208, in run
    result, is_end = self.curr_node.run(*args, wait_response=wait_response)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\features\feature_container.py", line 96, in run
    result = self.node_funcs["main"](*args)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\features\common_features.py", line 167, in signal_func
    self.model.active_microscope.prepare_next_channel()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\microscope.py", line 531, in prepare_next_channel
    self.daq.prepare_acquisition(channel_key, self.current_exposure_time)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\devices\daq\daq_ni.py", line 397, in prepare_acquisition
    self.create_analog_output_tasks(channel_key)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\devices\daq\daq_ni.py", line 365, in create_analog_output_tasks
    [
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\devices\daq\daq_ni.py", line 366, in <listcomp>
    v["waveform"][channel_key][:max_sample]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by zacsimile** [comment]
Only happens if you `focusout_validate` after pressing period. If you stay in the box, you're OK.

**Comment by zacsimile** [comment]
Two ways I can think of to fix this: 1) Make `ValidatedSpinbox._focusout_validate()` change a proposed value of `.` to `0.0` 2) Handle `.` in `GalvoBase`. I prefer 1), but I'm open to suggestions.
