### ISSUE TITLE
Eliminate Empty Positions Button

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#790]
The eliminate empty positions button needs to be wired up. 

![image](https://github.com/TheDeanLab/navigate/assets/42547789/1be3784a-e43e-4ab2-ab99-b4eb51f8ef65)

**Comment by AdvancedImagingUTSW** [comment]
Current status:

Works in synthetic mode, but something with the `.navigate/feature_list` folder is throwing an error on this machine...  Nothing obviously helpful in the logs.

Traceback
<details>

```

(navigate) C:\Users\Spectral>navigate
exposure_time Configuration Failed 0.00247066 0.0025941315789473683
load_feature called in model: (0,) <class 'int'>
Exception inside ObjectInSubprocess: Traceback (most recent call last):
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 526, in _child_loop
    result = getattr(obj, method_name)(*args, **kwargs)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\model.py", line 693, in run_command
    load_dynamic_parameter_functions(
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\features\feature_related_functions.py", line 379, in load_dynamic_parameter_functions
    ref_lib = parameter_config[parameter][args[idx]]
TypeError: unhashable type: 'SharedList'

load_feature called in model: (8,) <class 'int'>
Model (690) (8,)
Model (692) [{'name': <class 'navigate.model.features.common_features.PrepareNextChannel'>}, ({'name': <class 'navigate.model.features.common_features.MoveToNextPositionInMultiPositionTable'>}, {'name': <class 'navigate.model.features.remove_empty_tiles.DetectTissueInStackAndRecord'>, 'args': (5, 0.75, [])}, {'name': <class 'navigate.model.features.common_features.LoopByCount'>, 'args': ('experiment.MicroscopeState.multiposition_count',)}), {'name': <class 'navigate.model.features.remove_empty_tiles.RemoveEmptyPositions'>, 'args': ([],)}]
model thread exception happened! unhashable type: 'SharedList' Traceback (most recent call last):
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\controller\thread_pool.py", line 251, in func
    target(*args, **kwargs)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\controller\controller.py", line 693, in <lambda>
    "model", lambda: self.model.run_command("load_feature", *args)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 417, in attr
    return _get_response(self, True)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 438, in _get_response
    raise resp
Exception: unhashable type: 'SharedList'

model thread ended because of exception!: not all arguments converted during string formatting Traceback (most recent call last):
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\controller\thread_pool.py", line 251, in func
    target(*args, **kwargs)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\controller\controller.py", line 693, in <lambda>
    "model", lambda: self.model.run_command("load_feature", *args)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 417, in attr
    return _get_response(self, True)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 438, in _get_response
    raise resp
Exception: unhashable type: 'SharedList'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\controller\thread_pool.py", line 97, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\controller\thread_pool.py", line 259, in func
    logger.debug(
  File "C:\Users\Spectral\.conda\envs\navigate\lib\logging\__init__.py", line 1434, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\Users\Spectral\.conda\envs\navigate\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\Users\Spectral\.conda\envs\navigate\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\Users\Spectral\.conda\envs\navigate\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Spectral\.conda\envs\navigate\lib\logging\__init__.py", line 948, in handle
    rv = self.filter(record)
  File "C:\Users\Spectral\.conda\envs\navigate\lib\logging\__init__.py", line 806, in filter
    result = f.filter(record)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\log_files\filters.py", line 95, in filter
    if record.getMessage().startswith("Performance"):
  File "C:\Users\Spectral\.conda\envs\navigate\lib\logging\__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

Exception in thread model:
Traceback (most recent call last):
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\controller\thread_pool.py", line 251, in func
    target(*args, **kwargs)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\controller\controller.py", line 693, in <lambda>
    "model", lambda: self.model.run_command("load_feature", *args)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 417, in attr
    return _get_response(self, True)
  File "C:\Users\Spectral\Documents\GitHub\navigate\src\navigate\model\concurrency\concurrency_tools.py", line 438, in _get_response
    raise resp
Exception: unhashable type: 'SharedList'
```
</details>

`.navigate/feature_parameter_setting/RemoveEmptyPositions`:
```
{
    "position_flags": {
        "hard_threshold": "C:/Kevin/detect_tissue_hard_threshhold.py"
    }
}
```

**Comment by AdvancedImagingUTSW** [comment]
Okay, I opened `.navigate/feature_parameter_setting/RemoveEmptyPositions` and removed the "position_flags" entry. It is not just:

```
{}
```

I went back and tested the button, and now it works.
