### ISSUE TITLE
nidaqmx.errors.DaqError: Specified route cannot be satisfied

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#952]
2024-07-23 16:29:11,048 - model - INFO - daq_ni: Waveform Template Name: Default
2024-07-23 16:29:11,055 - model - INFO - daq_ni: Waveform Expand Num = 1
2024-07-23 16:29:11,055 - model - INFO - daq_ni: Waveform Repeat Num = 1
2024-07-23 16:29:11,401 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:11,401 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:11,401 - model - INFO - model: Navigate Model - Waiting 20
2024-07-23 16:29:11,901 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:11,901 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:11,901 - model - INFO - model: Navigate Model - Waiting 19
2024-07-23 16:29:12,404 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:12,404 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:12,404 - model - INFO - model: Navigate Model - Waiting 18
2024-07-23 16:29:12,905 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:12,905 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:12,905 - model - INFO - model: Navigate Model - Waiting 17
2024-07-23 16:29:13,407 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:13,407 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:13,407 - model - INFO - model: Navigate Model - Waiting 16
2024-07-23 16:29:13,908 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:13,908 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:13,908 - model - INFO - model: Navigate Model - Waiting 15
2024-07-23 16:29:14,408 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:14,408 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:14,408 - model - INFO - model: Navigate Model - Waiting 14
2024-07-23 16:29:14,910 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:14,910 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:14,910 - model - INFO - model: Navigate Model - Waiting 13
2024-07-23 16:29:15,411 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:15,411 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:15,411 - model - INFO - model: Navigate Model - Waiting 12
2024-07-23 16:29:15,911 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:15,911 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:15,911 - model - INFO - model: Navigate Model - Waiting 11
2024-07-23 16:29:16,411 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:16,411 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:16,411 - model - INFO - model: Navigate Model - Waiting 10
2024-07-23 16:29:16,913 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:16,913 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:16,913 - model - INFO - model: Navigate Model - Waiting 9
2024-07-23 16:29:17,414 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:17,414 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:17,414 - model - INFO - model: Navigate Model - Waiting 8
2024-07-23 16:29:17,915 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:17,915 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:17,915 - model - INFO - model: Navigate Model - Waiting 7
2024-07-23 16:29:18,418 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:18,418 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:18,419 - model - INFO - model: Navigate Model - Waiting 6
2024-07-23 16:29:18,920 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:18,920 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:18,920 - model - INFO - model: Navigate Model - Waiting 5
2024-07-23 16:29:19,421 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:19,421 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:19,421 - model - INFO - model: Navigate Model - Waiting 4
2024-07-23 16:29:19,923 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:19,923 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:19,923 - model - INFO - model: Navigate Model - Waiting 3
2024-07-23 16:29:20,174 - model - INFO - model: Navigate Model - Stopping with stop command.
2024-07-23 16:29:20,424 - model - DEBUG - HamamatsuAPI: error message: -2147483386
2024-07-23 16:29:20,424 - model - INFO - model: Navigate Model - Running data process, get frames []
2024-07-23 16:29:20,424 - model - INFO - model: Navigate Model - Waiting 2
2024-07-23 16:29:20,425 - model - INFO - model: Navigate Model - Data thread stopped.
2024-07-23 16:29:20,425 - model - INFO - model: Navigate Model - Received frames in total: 0
2024-07-23 16:29:22,055 - model - DEBUG - feature_container: running signal node: PrepareNextChannel
2024-07-23 16:29:22,140 - model - INFO - daq_ni: Waveform Template Name: Default
2024-07-23 16:29:22,151 - model - INFO - daq_ni: Waveform Expand Num = 1
2024-07-23 16:29:22,151 - model - INFO - daq_ni: Waveform Repeat Num = 1
2024-07-23 16:29:22,173 - model - DEBUG - feature_container: SignalContainer - Traceback (most recent call last):
  File "C:\Users\Dean-Lab\Desktop\navigate\src\navigate\model\features\feature_container.py", line 556, in run
    result, is_end = self.curr_node.run(*args, wait_response=wait_response)
  File "C:\Users\Dean-Lab\Desktop\navigate\src\navigate\model\features\feature_container.py", line 246, in run
    result = self.node_funcs["main"](*args)
  File "C:\Users\Dean-Lab\Desktop\navigate\src\navigate\model\features\common_features.py", line 513, in signal_func
    self.model.active_microscope.prepare_next_channel()
  File "C:\Users\Dean-Lab\Desktop\navigate\src\navigate\model\microscope.py", line 711, in prepare_next_channel
    self.daq.prepare_acquisition(channel_key)
  File "C:\Users\Dean-Lab\Desktop\navigate\src\navigate\model\devices\daq\daq_ni.py", line 348, in prepare_acquisition
    self.create_analog_output_tasks(channel_key)
  File "C:\Users\Dean-Lab\Desktop\navigate\src\navigate\model\devices\daq\daq_ni.py", line 318, in create_analog_output_tasks
    self.analog_output_tasks[board].write(waveforms)
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\task.py", line 1233, in write
    return _write_analog_f_64(
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\_task_modules\write_functions.py", line 32, in _write_analog_f_64
    check_for_error(error_code)
  File "C:\Users\Dean-Lab\miniconda3\envs\navigate\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: Specified route cannot be satisfied, because it requires resources that are currently in use by another route.
Property: DAQmx_DigEdge_StartTrig_Src
Property: DAQmx_DigEdge_StartTrig_Edge
Source Device: PCI6738
Source Terminal: Software

Required Resources in Use by
Task Name: _unnamedTask<19B>
Source Device: PCI6738
Source Terminal: PFI0
Destination Device: PCI6738
Destination Terminal: ao/StartTrigger

Task Name: _unnamedTask<1A6>

Status Code: -89137

[model_debug.log](https://github.com/user-attachments/files/16354485/model_debug.log)
[model_performance.log](https://github.com/user-attachments/files/16354486/model_performance.log)
[performance.log](https://github.com/user-attachments/files/16354487/performance.log)
[view_controller_debug.log](https://github.com/user-attachments/files/16354488/view_controller_debug.log)
[view_controller_info.log](https://github.com/user-attachments/files/16354489/view_controller_info.log)
[model_error.log](https://github.com/user-attachments/files/16354490/model_error.log)
[model_info.log](https://github.com/user-attachments/files/16354491/model_info.log)

**Comment by AdvancedImagingUTSW** [comment]
Assigned low priority label. Has only happened once to my knowledge. Will keep an eye out and see if this problem arises in the future. Do not address for now.
