### ISSUE TITLE
Plugin Install

### ISSUE THREAD

**Issue by JinlongL** [TheDeanLab/ASLM#990]
While trying to add a plugin via the plugin menu, we received this error:

```
(navigate) C:\Users\mesoO>navigate
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mesoO\.conda\envs\navigate\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\mesoO\OneDrive\Documents\GitHub\navigate\src\navigate\controller\sub_controllers\menus.py", line 1089, in install_plugin
    if plugin_name in plugins_dict:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by JinlongL** [comment]
Should have logic if this file is not found:

```
            plugins_dict = load_yaml_file(
                os.path.join(get_navigate_path(), "config", "plugins_config.yml")
            )
```
